=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/schema/component-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "name": "bse_basis_set_component",
    "version": "0.1",
    "url": "TODO",
    "description": "Basis Set Exchange - A component of a basis set",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "basis_set_description",
        "basis_set_elements"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "component" ]
                },
                "schema_version": {
                    "description": "Version of the BSE basis set component schema being used",
                    "type": "string"
                }
            }
        },
        "basis_set_description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "basis_set_notes": {
            "description": "Any notes pertaining to this basis set",
            "type": "string"
        },
        "basis_set_references": {
            "description": "Citation/Reference information for this basis set component",
            "type": "array",
            "minItems": 0,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "basis_set_elements": {
            "description": "Data for the elements of the basis set",
            "type": "object",
            "additionalProperties": false,
            "patternProperties":   {
                "^\\d+$" : {
                    "$ref" : "#/definitions/bse_basis_data"
                }
            }
        }
    },
    "definitions": {
        "bse_electron_shell": {
            "description": "Information for a single electronic shell",
            "additionalProperties": false,
            "required": [
                "shell_function_type",
                "shell_harmonic_type",
                "shell_region",
                "shell_angular_momentum",
                "shell_exponents",
                "shell_coefficients"
            ],
            "properties": {
                "shell_function_type": {
                    "description": "Type of function for this shell",
                    "type": "string",
                    "enum": [ "gto", "sto" ]
                },
                "shell_harmonic_type": {
                    "description": "Harmonic type (spherical, cartesian)",
                    "type": "string",
                    "enum": [ "spherical", "cartesian" ]
                },
                "shell_region": {
                    "description": "The region this shell describes",
                    "type": "string",
                    "enum": [ "", "valence", "polarization", "core", "tight", "diffuse" ]
                },
                "shell_angular_momentum": {
                    "description": "Angular momentum (as an array of integers)",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer",               
                        "minimum": 0
                    }
                },
                "shell_exponents": {
                    "description": "Exponents for this contracted shell",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "shell_coefficients": {
                    "description": "General contraction coefficients for this contracted shell",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "description": "Segmented contraction coefficients",
                        "type": "array",
                        "minItems": 1,
                        "items": { "type": "string" }
                    }
                }
            }
        },
        "ecp_potential": {
            "description": "ECP potential",
            "additionalProperties": false,
            "required": [
                "potential_ecp_type",
                "potential_angular_momentum",
                "potential_r_exponents",
                "potential_gaussian_exponents",
                "potential_coefficients"
            ],
            "properties": {
                "potential_ecp_type": {
                    "description": "Type of the ECP Potential",
                    "type": "string",
                    "enum": [ "scalar", "spinorbit" ]
                },
                "potential_angular_momentum": {
                    "description": "Angular momentum (as an array of integers)",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer",               
                        "minimum": 0
                    }
                },
                "potential_r_exponents": {
                    "description": "Exponents of the r term",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                },
                "potential_gaussian_exponents": {
                    "description": "Exponents of the gaussian term",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "potential_coefficients": {
                    "description": "General contraction coefficients for this contracted shell",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "description": "Segmented contraction coefficients",
                        "type": "array",
                        "minItems": 1,
                        "items": { "type": "string" }
                    }
                }
            }
        },
        "bse_basis_data": {
            "description": "Data for a single element or atom in the basis set",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "element_electron_shells": {
                    "description": "(Electronic) shells for this element",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "$ref": "#/definitions/bse_electron_shell"
                    }
                },
                "element_ecp_electrons":
                {
                    "description": "Number of electrons replaced by ECP",
                    "type": "integer",
                    "minimum": 1
                },
                "element_ecp": {
                    "description": "Effective Core Potential for this element",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "$ref": "#/definitions/ecp_potential"
                    }
                }
            }
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/pople/6-31G/6-31G-polarization_rassolov1998a.1.json
{
    "molssi_bse_schema": {
        "schema_type": "component",
        "schema_version": "0.1"
    },
    "basis_set_description": "Polarization for 6-31G split-valence basis set",
    "basis_set_references": [
        "rassolov1998a"
    ],
    "basis_set_elements": {
        "21": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        3
                    ],
                    "shell_exponents": [
                        "0.8000000000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                }
            ]
        },
        "22": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        3
                    ],
                    "shell_exponents": [
                        "0.8000000000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                }
            ]
        },
        "23": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        3
                    ],
                    "shell_exponents": [
                        "0.8000000000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                }
            ]
        },
        "24": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        3
                    ],
                    "shell_exponents": [
                        "0.8000000000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                }
            ]
        },
        "25": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        3
                    ],
                    "shell_exponents": [
                        "0.8000000000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                }
            ]
        },
        "26": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        3
                    ],
                    "shell_exponents": [
                        "0.8000000000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                }
            ]
        },
        "27": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        3
                    ],
                    "shell_exponents": [
                        "0.8000000000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                }
            ]
        },
        "28": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        3
                    ],
                    "shell_exponents": [
                        "0.8000000000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                }
            ]
        },
        "29": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        3
                    ],
                    "shell_exponents": [
                        "0.8000000000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                }
            ]
        },
        "30": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        3
                    ],
                    "shell_exponents": [
                        "0.8000000000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                }
            ]
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/dunning/cc-pV5Z_woon1994a.1.json
{
    "molssi_bse_schema": {
        "schema_type": "component",
        "schema_version": "0.1"
    },
    "basis_set_description": "The cc-pV5Z basis set",
    "basis_set_references": [
        "woon1994a"
    ],
    "basis_set_elements": {
        "2": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "1.145000E+03",
                        "1.717000E+02",
                        "3.907000E+01",
                        "1.104000E+01",
                        "3.566000E+00",
                        "1.240000E+00",
                        "4.473000E-01",
                        "1.640000E-01"
                    ],
                    "shell_coefficients": [
                        [
                            "3.590000E-04",
                            "2.771000E-03",
                            "1.425100E-02",
                            "5.556600E-02",
                            "1.620910E-01",
                            "3.321970E-01",
                            "4.196150E-01",
                            "1.861280E-01"
                        ],
                        [
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "1.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00"
                        ],
                        [
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "1.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00"
                        ],
                        [
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "1.000000E+00",
                            "0.000000E+00"
                        ],
                        [
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "1.000000E+00"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        1
                    ],
                    "shell_exponents": [
                        "1.015300E+01",
                        "3.627000E+00",
                        "1.296000E+00",
                        "4.630000E-01"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00"
                        ],
                        [
                            "0.000000E+00",
                            "1.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00"
                        ],
                        [
                            "0.000000E+00",
                            "0.000000E+00",
                            "1.000000E+00",
                            "0.000000E+00"
                        ],
                        [
                            "0.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00",
                            "1.000000E+00"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        2
                    ],
                    "shell_exponents": [
                        "7.666000E+00",
                        "2.647000E+00",
                        "9.140000E-01"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000E+00",
                            "0.000000E+00",
                            "0.000000E+00"
                        ],
                        [
                            "0.000000E+00",
                            "1.000000E+00",
                            "0.000000E+00"
                        ],
                        [
                            "0.000000E+00",
                            "0.000000E+00",
                            "1.000000E+00"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        3
                    ],
                    "shell_exponents": [
                        "5.411000E+00",
                        "1.707000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000E+00",
                            "0.000000E+00"
                        ],
                        [
                            "0.000000E+00",
                            "1.000000E+00"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        4
                    ],
                    "shell_exponents": [
                        "3.430000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                }
            ]
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/sto/bse_v0/STO-2G_hehre1969a.0.json
{
    "molssi_bse_schema": {
        "schema_type": "component",
        "schema_version": "0.1"
    },
    "basis_set_description": "STO-2G Minimal Basis (2 functions/AO)",
    "basis_set_references": [
        "hehre1969a"
    ],
    "basis_set_elements": {
        "1": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "1.309756377",
                        "0.233135974"
                    ],
                    "shell_coefficients": [
                        [
                            "0.430128498",
                            "0.678913531"
                        ]
                    ]
                }
            ]
        },
        "6": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "27.38503303",
                        "4.874522052"
                    ],
                    "shell_coefficients": [
                        [
                            "0.430128498",
                            "0.678913531"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "1.136748189",
                        "0.288309360"
                    ],
                    "shell_coefficients": [
                        [
                            "0.049471769",
                            "0.963782408"
                        ],
                        [
                            "0.511540708",
                            "0.612819896"
                        ]
                    ]
                }
            ]
        },
        "7": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "37.896475",
                        "6.745554"
                    ],
                    "shell_coefficients": [
                        [
                            "0.430128",
                            "0.678914"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "1.461089",
                        "0.370571"
                    ],
                    "shell_coefficients": [
                        [
                            "0.049472",
                            "0.963782"
                        ],
                        [
                            "0.511541",
                            "0.612820"
                        ]
                    ]
                }
            ]
        },
        "8": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "49.980971",
                        "8.896588"
                    ],
                    "shell_coefficients": [
                        [
                            "0.430128",
                            "0.678914"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "1.945237",
                        "0.493363"
                    ],
                    "shell_coefficients": [
                        [
                            "0.049472",
                            "0.963782"
                        ],
                        [
                            "0.511541",
                            "0.612820"
                        ]
                    ]
                }
            ]
        },
        "9": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "63.735202",
                        "11.344834"
                    ],
                    "shell_coefficients": [
                        [
                            "0.430128",
                            "0.678914"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "2.498548",
                        "0.633698"
                    ],
                    "shell_coefficients": [
                        [
                            "0.049472",
                            "0.963782"
                        ],
                        [
                            "0.511541",
                            "0.612820"
                        ]
                    ]
                }
            ]
        }
    }
}
