=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/schema/component-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "name": "bse_basis_set_component",
    "version": "0.1",
    "url": "TODO",
    "description": "Basis Set Exchange - A component of a basis set",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "basis_set_description",
        "basis_set_elements"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "component" ]
                },
                "schema_version": {
                    "description": "Version of the BSE basis set component schema being used",
                    "type": "string"
                }
            }
        },
        "basis_set_description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "basis_set_notes": {
            "description": "Any notes pertaining to this basis set",
            "type": "string"
        },
        "basis_set_references": {
            "description": "Citation/Reference information for this basis set component",
            "type": "array",
            "minItems": 0,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "basis_set_elements": {
            "description": "Data for the elements of the basis set",
            "type": "object",
            "additionalProperties": false,
            "patternProperties":   {
                "^\\d+$" : {
                    "$ref" : "#/definitions/bse_basis_data"
                }
            }
        }
    },
    "definitions": {
        "bse_electron_shell": {
            "description": "Information for a single electronic shell",
            "additionalProperties": false,
            "required": [
                "shell_function_type",
                "shell_harmonic_type",
                "shell_region",
                "shell_angular_momentum",
                "shell_exponents",
                "shell_coefficients"
            ],
            "properties": {
                "shell_function_type": {
                    "description": "Type of function for this shell",
                    "type": "string",
                    "enum": [ "gto", "sto" ]
                },
                "shell_harmonic_type": {
                    "description": "Harmonic type (spherical, cartesian)",
                    "type": "string",
                    "enum": [ "spherical", "cartesian" ]
                },
                "shell_region": {
                    "description": "The region this shell describes",
                    "type": "string",
                    "enum": [ "", "valence", "polarization", "core", "tight", "diffuse" ]
                },
                "shell_angular_momentum": {
                    "description": "Angular momentum (as an array of integers)",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer",               
                        "minimum": 0
                    }
                },
                "shell_exponents": {
                    "description": "Exponents for this contracted shell",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "shell_coefficients": {
                    "description": "General contraction coefficients for this contracted shell",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "description": "Segmented contraction coefficients",
                        "type": "array",
                        "minItems": 1,
                        "items": { "type": "string" }
                    }
                }
            }
        },
        "ecp_potential": {
            "description": "ECP potential",
            "additionalProperties": false,
            "required": [
                "potential_ecp_type",
                "potential_angular_momentum",
                "potential_r_exponents",
                "potential_gaussian_exponents",
                "potential_coefficients"
            ],
            "properties": {
                "potential_ecp_type": {
                    "description": "Type of the ECP Potential",
                    "type": "string",
                    "enum": [ "scalar", "spinorbit" ]
                },
                "potential_angular_momentum": {
                    "description": "Angular momentum (as an array of integers)",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer",               
                        "minimum": 0
                    }
                },
                "potential_r_exponents": {
                    "description": "Exponents of the r term",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                },
                "potential_gaussian_exponents": {
                    "description": "Exponents of the gaussian term",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "potential_coefficients": {
                    "description": "General contraction coefficients for this contracted shell",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "description": "Segmented contraction coefficients",
                        "type": "array",
                        "minItems": 1,
                        "items": { "type": "string" }
                    }
                }
            }
        },
        "bse_basis_data": {
            "description": "Data for a single element or atom in the basis set",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "element_electron_shells": {
                    "description": "(Electronic) shells for this element",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "$ref": "#/definitions/bse_electron_shell"
                    }
                },
                "element_ecp_electrons":
                {
                    "description": "Number of electrons replaced by ECP",
                    "type": "integer",
                    "minimum": 1
                },
                "element_ecp": {
                    "description": "Effective Core Potential for this element",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "$ref": "#/definitions/ecp_potential"
                    }
                }
            }
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/pople/bse_v0/6-311G-dp-polarization_curtiss1995a.0.json
{
    "molssi_bse_schema": {
        "schema_type": "component",
        "schema_version": "0.1"
    },
    "basis_set_description": "1P      Polarization functions associated with 6-311G",
    "basis_set_references": [
        "curtiss1995a"
    ],
    "basis_set_elements": {
        "31": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "polarization",
                    "shell_angular_momentum": [
                        2
                    ],
                    "shell_exponents": [
                        "0.169000"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000"
                        ]
                    ]
                }
            ]
        },
        "32": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "polarization",
                    "shell_angular_momentum": [
                        2
                    ],
                    "shell_exponents": [
                        "0.228000"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000"
                        ]
                    ]
                }
            ]
        },
        "33": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "polarization",
                    "shell_angular_momentum": [
                        2
                    ],
                    "shell_exponents": [
                        "0.264000"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000"
                        ]
                    ]
                }
            ]
        },
        "34": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "polarization",
                    "shell_angular_momentum": [
                        2
                    ],
                    "shell_exponents": [
                        "0.305000"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000"
                        ]
                    ]
                }
            ]
        },
        "35": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "polarization",
                    "shell_angular_momentum": [
                        2
                    ],
                    "shell_exponents": [
                        "0.451000"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000"
                        ]
                    ]
                }
            ]
        },
        "36": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "polarization",
                    "shell_angular_momentum": [
                        2
                    ],
                    "shell_exponents": [
                        "0.395000"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000"
                        ]
                    ]
                }
            ]
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/ahlrichs/bse_v0/QZV/def2-QZVPD-base_weigend2005a.0.json
{
    "molssi_bse_schema": {
        "schema_type": "component",
        "schema_version": "0.1"
    },
    "basis_set_description": "Common base shells for def2-QZV*",
    "basis_set_references": [
        "weigend2005a"
    ],
    "basis_set_elements": {
        "56": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "5.7000000000",
                        "5.2043612469"
                    ],
                    "shell_coefficients": [
                        [
                            "1.3292982002",
                            "-1.7367497134"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "2.1475437282"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "0.41033660537"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "0.18393532770"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "0.72521216545E-01"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "0.34526334903E-01"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "0.16157891872E-01"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        1
                    ],
                    "shell_exponents": [
                        "5.6000000000",
                        "5.1104879274",
                        "2.5006544803",
                        "0.51947995345"
                    ],
                    "shell_coefficients": [
                        [
                            "0.51385026013",
                            "-0.70529238864",
                            "0.42822329830",
                            "-0.57125984472"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        1
                    ],
                    "shell_exponents": [
                        "0.24536994841"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        1
                    ],
                    "shell_exponents": [
                        "0.11256056700"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        1
                    ],
                    "shell_exponents": [
                        "0.34917622027E-01"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        1
                    ],
                    "shell_exponents": [
                        "0.16320065666E-01"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        2
                    ],
                    "shell_exponents": [
                        "2.7000000000",
                        "2.3460740881",
                        "0.39553542609"
                    ],
                    "shell_coefficients": [
                        [
                            ".14372069824",
                            "-.19565347309",
                            ".29963058552"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        2
                    ],
                    "shell_exponents": [
                        "0.12967935859"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        2
                    ],
                    "shell_exponents": [
                        "0.40463066544E-01"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000"
                        ]
                    ]
                }
            ]
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/tests/fakedata/fake/bppfakebasis_fakeref2019a.1.json
{
    "molssi_bse_schema": {
        "schema_type": "component",
        "schema_version": "0.1"
    },
    "basis_set_description": "A fake basis set for testing the BSE",
    "basis_set_references": [
        "fakeref2019a"
    ],
    "basis_set_elements": {
        "1": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "1.0000000000E+00"
                    ],
                    "shell_coefficients": [
                        [
                            "1.0000000000E+00"
                        ]
                    ]
                }
            ]
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/ahlrichs/ECP/def2-ECP_leininger1996a.1.json
{
    "molssi_bse_schema": {
        "schema_type": "component",
        "schema_version": "0.1"
    },
    "basis_set_description": "def2-ECP",
    "basis_set_references": [
        "leininger1996a"
    ],
    "basis_set_elements": {
        "37": {
            "element_ecp_electrons": 28,
            "element_ecp": [
                {
                    "potential_ecp_type": "scalar",
                    "potential_angular_momentum": [
                        3
                    ],
                    "potential_r_exponents": [
                        2
                    ],
                    "potential_gaussian_exponents": [
                        "3.8431140"
                    ],
                    "potential_coefficients": [
                        [
                            "-12.3169000"
                        ]
                    ]
                },
                {
                    "potential_ecp_type": "scalar",
                    "potential_angular_momentum": [
                        0
                    ],
                    "potential_r_exponents": [
                        2,
                        2,
                        2
                    ],
                    "potential_gaussian_exponents": [
                        "5.0365510",
                        "1.9708490",
                        "3.8431140"
                    ],
                    "potential_coefficients": [
                        [
                            "89.5001980",
                            "0.4937610",
                            "12.3169000"
                        ]
                    ]
                },
                {
                    "potential_ecp_type": "scalar",
                    "potential_angular_momentum": [
                        1
                    ],
                    "potential_r_exponents": [
                        2,
                        2,
                        2
                    ],
                    "potential_gaussian_exponents": [
                        "4.2583410",
                        "1.4707090",
                        "3.8431140"
                    ],
                    "potential_coefficients": [
                        [
                            "58.5689740",
                            "0.4317910",
                            "12.3169000"
                        ]
                    ]
                },
                {
                    "potential_ecp_type": "scalar",
                    "potential_angular_momentum": [
                        2
                    ],
                    "potential_r_exponents": [
                        2,
                        2,
                        2
                    ],
                    "potential_gaussian_exponents": [
                        "3.0231270",
                        "0.6503830",
                        "3.8431140"
                    ],
                    "potential_coefficients": [
                        [
                            "26.2248980",
                            "0.9628390",
                            "12.3169000"
                        ]
                    ]
                }
            ]
        },
        "55": {
            "element_ecp_electrons": 46,
            "element_ecp": [
                {
                    "potential_ecp_type": "scalar",
                    "potential_angular_momentum": [
                        3
                    ],
                    "potential_r_exponents": [
                        2
                    ],
                    "potential_gaussian_exponents": [
                        "3.1232690"
                    ],
                    "potential_coefficients": [
                        [
                            "-28.8843090"
                        ]
                    ]
                },
                {
                    "potential_ecp_type": "scalar",
                    "potential_angular_momentum": [
                        0
                    ],
                    "potential_r_exponents": [
                        2,
                        2,
                        2
                    ],
                    "potential_gaussian_exponents": [
                        "4.0797500",
                        "2.4174060",
                        "3.1232690"
                    ],
                    "potential_coefficients": [
                        [
                            "84.5477300",
                            "16.6541730",
                            "28.8843090"
                        ]
                    ]
                },
                {
                    "potential_ecp_type": "scalar",
                    "potential_angular_momentum": [
                        1
                    ],
                    "potential_r_exponents": [
                        2,
                        2,
                        2
                    ],
                    "potential_gaussian_exponents": [
                        "5.5140800",
                        "2.1603160",
                        "3.1232690"
                    ],
                    "potential_coefficients": [
                        [
                            "157.0490590",
                            "26.4233070",
                            "28.8843090"
                        ]
                    ]
                },
                {
                    "potential_ecp_type": "scalar",
                    "potential_angular_momentum": [
                        2
                    ],
                    "potential_r_exponents": [
                        2,
                        2,
                        2
                    ],
                    "potential_gaussian_exponents": [
                        "1.8074100",
                        "0.8581820",
                        "3.1232690"
                    ],
                    "potential_coefficients": [
                        [
                            "13.1727530",
                            "3.3428330",
                            "28.8843090"
                        ]
                    ]
                }
            ]
        }
    }
}
