=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/schema/component-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "name": "bse_basis_set_component",
    "version": "0.1",
    "url": "TODO",
    "description": "Basis Set Exchange - A component of a basis set",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "basis_set_description",
        "basis_set_elements"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "component" ]
                },
                "schema_version": {
                    "description": "Version of the BSE basis set component schema being used",
                    "type": "string"
                }
            }
        },
        "basis_set_description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "basis_set_notes": {
            "description": "Any notes pertaining to this basis set",
            "type": "string"
        },
        "basis_set_references": {
            "description": "Citation/Reference information for this basis set component",
            "type": "array",
            "minItems": 0,
            "uniqueItems": true,
            "items": {
                "type": "string"
            }
        },
        "basis_set_elements": {
            "description": "Data for the elements of the basis set",
            "type": "object",
            "additionalProperties": false,
            "patternProperties":   {
                "^\\d+$" : {
                    "$ref" : "#/definitions/bse_basis_data"
                }
            }
        }
    },
    "definitions": {
        "bse_electron_shell": {
            "description": "Information for a single electronic shell",
            "additionalProperties": false,
            "required": [
                "shell_function_type",
                "shell_harmonic_type",
                "shell_region",
                "shell_angular_momentum",
                "shell_exponents",
                "shell_coefficients"
            ],
            "properties": {
                "shell_function_type": {
                    "description": "Type of function for this shell",
                    "type": "string",
                    "enum": [ "gto", "sto" ]
                },
                "shell_harmonic_type": {
                    "description": "Harmonic type (spherical, cartesian)",
                    "type": "string",
                    "enum": [ "spherical", "cartesian" ]
                },
                "shell_region": {
                    "description": "The region this shell describes",
                    "type": "string",
                    "enum": [ "", "valence", "polarization", "core", "tight", "diffuse" ]
                },
                "shell_angular_momentum": {
                    "description": "Angular momentum (as an array of integers)",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer",               
                        "minimum": 0
                    }
                },
                "shell_exponents": {
                    "description": "Exponents for this contracted shell",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "shell_coefficients": {
                    "description": "General contraction coefficients for this contracted shell",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "description": "Segmented contraction coefficients",
                        "type": "array",
                        "minItems": 1,
                        "items": { "type": "string" }
                    }
                }
            }
        },
        "ecp_potential": {
            "description": "ECP potential",
            "additionalProperties": false,
            "required": [
                "potential_ecp_type",
                "potential_angular_momentum",
                "potential_r_exponents",
                "potential_gaussian_exponents",
                "potential_coefficients"
            ],
            "properties": {
                "potential_ecp_type": {
                    "description": "Type of the ECP Potential",
                    "type": "string",
                    "enum": [ "scalar", "spinorbit" ]
                },
                "potential_angular_momentum": {
                    "description": "Angular momentum (as an array of integers)",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "type": "integer",               
                        "minimum": 0
                    }
                },
                "potential_r_exponents": {
                    "description": "Exponents of the r term",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "integer"
                    }
                },
                "potential_gaussian_exponents": {
                    "description": "Exponents of the gaussian term",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "type": "string"
                    }
                },
                "potential_coefficients": {
                    "description": "General contraction coefficients for this contracted shell",
                    "type": "array",
                    "minItems": 1,
                    "items": {
                        "description": "Segmented contraction coefficients",
                        "type": "array",
                        "minItems": 1,
                        "items": { "type": "string" }
                    }
                }
            }
        },
        "bse_basis_data": {
            "description": "Data for a single element or atom in the basis set",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "element_electron_shells": {
                    "description": "(Electronic) shells for this element",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "$ref": "#/definitions/bse_electron_shell"
                    }
                },
                "element_ecp_electrons":
                {
                    "description": "Number of electrons replaced by ECP",
                    "type": "integer",
                    "minimum": 1
                },
                "element_ecp": {
                    "description": "Effective Core Potential for this element",
                    "type": "array",
                    "minItems": 1,
                    "uniqueItems": true,
                    "items": {
                        "$ref": "#/definitions/ecp_potential"
                    }
                }
            }
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/sto/bse_v0/STO-3G_hehre1969a_hehre1970a.0.json
{
    "molssi_bse_schema": {
        "schema_type": "component",
        "schema_version": "0.1"
    },
    "basis_set_description": "STO-3G Minimal Basis (3 functions/AO)",
    "basis_set_references": [
        "hehre1969a",
        "hehre1970a"
    ],
    "basis_set_notes": "Uses base information from hehre1969a, with molecular Slater coefficients from hehre1970a",
    "basis_set_elements": {
        "2": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "6.36242139",
                        "1.15892300",
                        "0.31364979"
                    ],
                    "shell_coefficients": [
                        [
                            "0.15432897",
                            "0.53532814",
                            "0.44463454"
                        ]
                    ]
                }
            ]
        },
        "3": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "16.119575",
                        "2.9362007",
                        "0.7946505"
                    ],
                    "shell_coefficients": [
                        [
                            "0.15432897",
                            "0.53532814",
                            "0.44463454"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "0.6362897",
                        "0.1478601",
                        "0.0480887"
                    ],
                    "shell_coefficients": [
                        [
                            "-0.09996723",
                            "0.39951283",
                            "0.70011547"
                        ],
                        [
                            "0.15591627",
                            "0.60768372",
                            "0.39195739"
                        ]
                    ]
                }
            ]
        },
        "4": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "30.167871",
                        "5.4951153",
                        "1.4871927"
                    ],
                    "shell_coefficients": [
                        [
                            "0.15432897",
                            "0.53532814",
                            "0.44463454"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "1.3148331",
                        "0.3055389",
                        "0.0993707"
                    ],
                    "shell_coefficients": [
                        [
                            "-0.09996723",
                            "0.39951283",
                            "0.70011547"
                        ],
                        [
                            "0.15591627",
                            "0.60768372",
                            "0.39195739"
                        ]
                    ]
                }
            ]
        },
        "5": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "48.791113",
                        "8.8873622",
                        "2.4052670"
                    ],
                    "shell_coefficients": [
                        [
                            "0.15432897",
                            "0.53532814",
                            "0.44463454"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "2.2369561",
                        "0.5198205",
                        "0.1690618"
                    ],
                    "shell_coefficients": [
                        [
                            "-0.09996723",
                            "0.39951283",
                            "0.70011547"
                        ],
                        [
                            "0.15591627",
                            "0.60768372",
                            "0.39195739"
                        ]
                    ]
                }
            ]
        },
        "10": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "207.01561",
                        "37.708151",
                        "10.205297"
                    ],
                    "shell_coefficients": [
                        [
                            "0.15432897",
                            "0.53532814",
                            "0.44463454"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "8.2463151",
                        "1.9162662",
                        "0.6232293"
                    ],
                    "shell_coefficients": [
                        [
                            "-0.09996723",
                            "0.39951283",
                            "0.70011547"
                        ],
                        [
                            "0.15591627",
                            "0.60768372",
                            "0.39195739"
                        ]
                    ]
                }
            ]
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/pople/bse_v0/4-31G_ditchfield1971a.0.json
{
    "molssi_bse_schema": {
        "schema_type": "component",
        "schema_version": "0.1"
    },
    "basis_set_description": "4-31G valence double-zeta",
    "basis_set_references": [
        "ditchfield1971a"
    ],
    "basis_set_elements": {
        "6": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "486.96693",
                        "73.371094",
                        "16.413458",
                        "4.3449836"
                    ],
                    "shell_coefficients": [
                        [
                            "0.0177258",
                            "0.1234787",
                            "0.4338754",
                            "0.5615042"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "8.6735253",
                        "2.0966193",
                        "0.6046513"
                    ],
                    "shell_coefficients": [
                        [
                            "-0.1213837",
                            "-0.2273385",
                            "1.1851739"
                        ],
                        [
                            "0.0635454",
                            "0.2982678",
                            "0.7621032"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "0.1835578"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000"
                        ],
                        [
                            "1.000000"
                        ]
                    ]
                }
            ]
        },
        "7": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "671.2795",
                        "101.2017",
                        "22.69997",
                        "6.040609"
                    ],
                    "shell_coefficients": [
                        [
                            "0.0175982511",
                            "0.1228462410",
                            "0.4337821410",
                            "0.5614182170"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "12.3935997",
                        "2.9223828",
                        "0.83252808"
                    ],
                    "shell_coefficients": [
                        [
                            "-0.1174892990",
                            "-0.2139940160",
                            "1.1745021100"
                        ],
                        [
                            "0.0640203443",
                            "0.3112025550",
                            "0.7527482390"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "0.2259640"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000"
                        ],
                        [
                            "1.000000"
                        ]
                    ]
                }
            ]
        },
        "8": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "883.27286",
                        "133.12928",
                        "29.906408",
                        "7.9786772"
                    ],
                    "shell_coefficients": [
                        [
                            "0.0175506",
                            "0.1228292",
                            "0.4348836",
                            "0.5600108"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "16.194447",
                        "3.7800860",
                        "1.0709836"
                    ],
                    "shell_coefficients": [
                        [
                            "-0.1134010",
                            "-0.1772865",
                            "1.1504079"
                        ],
                        [
                            "0.0685453",
                            "0.3312254",
                            "0.7346079"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "0.2838798"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000"
                        ],
                        [
                            "1.000000"
                        ]
                    ]
                }
            ]
        },
        "9": {
            "element_electron_shells": [
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        0
                    ],
                    "shell_exponents": [
                        "1126.163",
                        "169.7432",
                        "38.18151",
                        "10.21204"
                    ],
                    "shell_coefficients": [
                        [
                            "0.0174758",
                            "0.122523",
                            "0.434999",
                            "0.559812"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "21.495370",
                        "4.989778",
                        "1.403574"
                    ],
                    "shell_coefficients": [
                        [
                            "-0.111057",
                            "-0.168322",
                            "1.143626"
                        ],
                        [
                            "0.069888",
                            "0.339388",
                            "0.727959"
                        ]
                    ]
                },
                {
                    "shell_function_type": "gto",
                    "shell_harmonic_type": "spherical",
                    "shell_region": "valence",
                    "shell_angular_momentum": [
                        0,
                        1
                    ],
                    "shell_exponents": [
                        "0.3730318"
                    ],
                    "shell_coefficients": [
                        [
                            "1.000000"
                        ],
                        [
                            "1.000000"
                        ]
                    ]
                }
            ]
        }
    }
}
