=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/schema/element-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "name": "bse_element_basis_set",
    "version": "0.1",
    "url": "TODO",
    "description": "JSON for describing how a element-based basis set is composed",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "basis_set_name",
        "basis_set_description",
        "basis_set_elements"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "element" ]
                },
                "schema_version": {
                    "description": "Version of the BSE element basis set schema being used",
                    "type": "string"
                }
            }
        },
        "basis_set_name": {
            "description": "Common name for the basis set",
            "type": "string"
        },
        "basis_set_description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "basis_set_notes": {
            "description": "Any notes pertaining to this basis set",
            "type": "string"
        },
        "basis_set_elements": {
            "description": "Data for the elements of the basis set",
            "type": "object",
            "additionalProperties": false,
            "patternProperties":   {
                "^\\d+$" : {
                    "description": "Data for a single element in the basis set",
                    "type": "object",
                    "additionalProperties": false,
                    "required": [ "element_components" ],
                    "properties": {
                        "element_components": {
                            "description": "Component files for this element",
                            "type": "array",
                            "minItems": 1,
                            "uniqueItems": true,
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/ahlrichs_fit/def2-SV(P)-JKFIT.1.element.json
{
    "molssi_bse_schema": {
        "schema_type": "element",
        "schema_version": "0.1"
    },
    "basis_set_name": "def2-SV(P)-JKFIT",
    "basis_set_description": "Coulomb/Exchange fitting auxiliary basis for def2-SV(P)",
    "basis_set_notes": "The JKFit for La/def2-SV(P) is different than the 'universal' JKFit",
    "basis_set_elements": {
        "57": {
            "element_components": [
                "ahlrichs_fit/def2-SV(P)-JKFIT_weigend2008a.1.json"
            ]
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/ahlrichs/bse_v0/def2-SV(P).0.element.json
{
    "molssi_bse_schema": {
        "schema_type": "element",
        "schema_version": "0.1"
    },
    "basis_set_name": "def2-SV(P)",
    "basis_set_description": "def2-SV(P)",
    "basis_set_elements": {
        "56": {
            "element_components": [
                "ahlrichs/bse_v0/SV/def2-SV-base_weigend2005a.0.json",
                "ahlrichs/ECP/def2-ECP_kaupp1991a.1.json"
            ]
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/pople/bse_v0/6-31PPG.0.element.json
{
    "molssi_bse_schema": {
        "schema_type": "element",
        "schema_version": "0.1"
    },
    "basis_set_name": "6-31++G",
    "basis_set_description": "Pople 6-31++G basis set",
    "basis_set_elements": {
        "1": {
            "element_components": [
                "pople/bse_v0/6-31G-H-BSE_ditchfield1971a.0.json",
                "pople/bse_v0/6-31G-diffuse_clark1983a.0.json"
            ]
        },
        "3": {
            "element_components": [
                "pople/bse_v0/6-31G_dill1975a.0.json",
                "pople/bse_v0/6-31G-diffuse_clark1983a.0.json"
            ]
        },
        "4": {
            "element_components": [
                "pople/bse_v0/6-31G_binkley1977a.0.json",
                "pople/bse_v0/6-31G-diffuse_clark1983a.0.json"
            ]
        },
        "5": {
            "element_components": [
                "pople/bse_v0/6-31G_dill1975a.0.json",
                "pople/bse_v0/6-31G-diffuse_clark1983a.0.json"
            ]
        },
        "6": {
            "element_components": [
                "pople/bse_v0/6-31G_hehre1972a.0.json",
                "pople/bse_v0/6-31G-diffuse_clark1983a.0.json"
            ]
        },
        "7": {
            "element_components": [
                "pople/bse_v0/6-31G_hehre1972a.0.json",
                "pople/bse_v0/6-31G-diffuse_clark1983a.0.json"
            ]
        },
        "8": {
            "element_components": [
                "pople/bse_v0/6-31G_hehre1972a.0.json",
                "pople/bse_v0/6-31G-diffuse_clark1983a.0.json"
            ]
        },
        "9": {
            "element_components": [
                "pople/bse_v0/6-31G_hehre1972a.0.json",
                "pople/bse_v0/6-31G-diffuse_clark1983a.0.json"
            ]
        },
        "10": {
            "element_components": [
                "pople/bse_v0/6-31G_noref.0.json",
                "pople/bse_v0/6-31G-diffuse_gill1992a.0.json"
            ]
        },
        "11": {
            "element_components": [
                "pople/bse_v0/6-21G-core_gordon1982a.0.json",
                "pople/bse_v0/6-31G-valence_francl1982a.0.json",
                "pople/bse_v0/6-31G-diffuse_spitznagel1987a.0.json"
            ]
        },
        "12": {
            "element_components": [
                "pople/bse_v0/6-21G-core_gordon1982a.0.json",
                "pople/bse_v0/6-31G-valence_francl1982a.0.json",
                "pople/bse_v0/6-31G-diffuse_spitznagel1987a.0.json"
            ]
        },
        "13": {
            "element_components": [
                "pople/bse_v0/6-21G-core_gordon1982a.0.json",
                "pople/bse_v0/6-31G-valence_francl1982a.0.json",
                "pople/bse_v0/6-31G-diffuse_spitznagel1987a.0.json"
            ]
        },
        "14": {
            "element_components": [
                "pople/bse_v0/6-21G-core_gordon1982a.0.json",
                "pople/bse_v0/6-31G-valence_francl1982a.0.json",
                "pople/bse_v0/6-31G-diffuse_spitznagel1987a.0.json"
            ]
        },
        "15": {
            "element_components": [
                "pople/bse_v0/6-21G-core_gordon1982a.0.json",
                "pople/bse_v0/6-31G-valence_francl1982a.0.json",
                "pople/bse_v0/6-31G-diffuse_spitznagel1987a.0.json"
            ]
        },
        "16": {
            "element_components": [
                "pople/bse_v0/6-21G-core_gordon1982a.0.json",
                "pople/bse_v0/6-31G-valence_francl1982a.0.json",
                "pople/bse_v0/6-31G-diffuse_spitznagel1987a.0.json"
            ]
        },
        "17": {
            "element_components": [
                "pople/bse_v0/6-21G-core_gordon1982a.0.json",
                "pople/bse_v0/6-31G-valence_francl1982a.0.json",
                "pople/bse_v0/6-31G-diffuse_spitznagel1987a.0.json"
            ]
        },
        "18": {
            "element_components": [
                "pople/bse_v0/6-21G-core_gordon1982a.0.json",
                "pople/bse_v0/6-31G-valence_francl1982a.0.json",
                "pople/bse_v0/6-31G-diffuse_gill1992a.0.json"
            ]
        },
        "19": {
            "element_components": [
                "pople/bse_v0/6-31G_rassolov1998a.0.json",
                "pople/bse_v0/6-31G-diffuse_noref.0.json"
            ]
        },
        "20": {
            "element_components": [
                "pople/bse_v0/6-31G_rassolov1998a.0.json",
                "pople/bse_v0/6-31G-diffuse_noref.0.json"
            ]
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/dunning_fit/bse_v0/cc-pVTZ-RIFIT.0.element.json
{
    "molssi_bse_schema": {
        "schema_type": "element",
        "schema_version": "0.1"
    },
    "basis_set_name": "cc-pVTZ-RIFIT",
    "basis_set_description": "cc-pVTZ-RIFIT",
    "basis_set_elements": {
        "1": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "2": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "3": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_hattig2005a.0.json"
            ]
        },
        "4": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_hattig2005a.0.json"
            ]
        },
        "5": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "6": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "7": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "8": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "9": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "10": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "11": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_hattig2005a.0.json"
            ]
        },
        "12": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_hattig2005a.0.json"
            ]
        },
        "13": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "14": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "15": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "16": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "17": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "18": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "31": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "32": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "33": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "34": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "35": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        },
        "36": {
            "element_components": [
                "dunning_fit/bse_v0/cc-pVTZ-RIFIT_weigend2002a.0.json"
            ]
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/dunning_fit/cc-pVTZ-JKFIT.1.element.json
{
    "molssi_bse_schema": {
        "schema_type": "element",
        "schema_version": "0.1"
    },
    "basis_set_name": "cc-pVTZ-JKFIT",
    "basis_set_description": "JK Fitting basis for use with cc-pVTZ",
    "basis_set_elements": {
        "1": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "5": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "6": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "7": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "8": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "9": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "13": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "14": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "15": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "16": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "17": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "31": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "32": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "33": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "34": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        },
        "35": {
            "element_components": [
                "dunning_fit/cc-pVTZ-JKFIT_weigend2002b.1.json"
            ]
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/jensen/pcJ-3.1.element.json
{
    "molssi_bse_schema": {
        "schema_type": "element",
        "schema_version": "0.1"
    },
    "basis_set_name": "pcJ-3",
    "basis_set_description": "Contracted version of the pcJ-3 basis",
    "basis_set_elements": {
        "1": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "2": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "3": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "4": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "5": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "6": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "7": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "8": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "9": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "10": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "11": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "12": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "13": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "14": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "15": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "16": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "17": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        },
        "18": {
            "element_components": [
                "jensen/pcJ-3_jensen2010a.1.json"
            ]
        }
    }
}
