=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/schema/metadata-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "name": "bse_basis_metadata",
    "version": "0.1",
    "url": "TODO",
    "description": "JSON for describing metadata for a single basis set",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "basis_set_name",
        "basis_set_family",
        "basis_set_description",
        "basis_set_role",
        "basis_set_auxiliaries"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "metadata" ]
                },
                "schema_version": {
                    "description": "Version of the BSE table basis set schema being used",
                    "type": "string"
                }
            }
        },
        "basis_set_name": {
            "description": "Common name for the basis set",
            "type": "string"
        },
        "basis_set_family": {
            "description": "Broad family that the basis set is from",
            "type": "string"
        },
        "basis_set_description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "basis_set_role": {
            "description": "Role that this basis plays in a calculation",
            "type": "string",
            "enum": [ "orbital", "rifit", "jkfit", "jfit", "admmfit", "dftxfit", "dftcfit"]
        },
        "basis_set_auxiliaries": {
            "description": "Auxiliary basis sets (fitting, etc) and how their role with his basis",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "jfit" : { "type": "string" },
                "jkfit" : { "type": "string" },
                "rifit" : { "type": "string" },
                "admmfit" : { "type": "string" },
                "dftxfit": { "type": "string" },
                "dftcfit": { "type": "string" }
            }
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/cc-pV6Z-RIFIT.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "basis_set_name": "cc-pV6Z-RIFIT",
    "basis_set_family": "dunning_fit",
    "basis_set_description": "RI Fitting basis for use with cc-pV6Z",
    "basis_set_role": "rifit",
    "basis_set_auxiliaries": {}
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/pcJ-4.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "basis_set_name": "pcJ-4",
    "basis_set_family": "jensen",
    "basis_set_description": "Contracted version of the pcJ-4 basis",
    "basis_set_role": "orbital",
    "basis_set_auxiliaries": {}
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/aug-cc-pVD+dZ.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "basis_set_name": "aug-cc-pV(D+d)Z",
    "basis_set_family": "dunning",
    "basis_set_description": "aug-cc-pV(D+d)Z",
    "basis_set_role": "orbital",
    "basis_set_auxiliaries": {
        "rifit": "aug-cc-pvdz-rifit"
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/6ZP.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "basis_set_name": "jorge-6ZP",
    "basis_set_family": "jorge",
    "basis_set_description": "6ZP: 6 zeta valence quality plus polarization",
    "basis_set_role": "orbital",
    "basis_set_auxiliaries": {}
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/pcseg-4.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "basis_set_name": "pcseg-4",
    "basis_set_family": "jensen",
    "basis_set_description": "Segmented contracted version of the pc-4 basis",
    "basis_set_role": "orbital",
    "basis_set_auxiliaries": {}
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/ATZP.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "basis_set_name": "jorge-ATZP",
    "basis_set_family": "jorge",
    "basis_set_description": "ATZP: Augmented triple zeta valence quality plus polarization",
    "basis_set_role": "orbital",
    "basis_set_auxiliaries": {}
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/IGLOII.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "basis_set_name": "IGLO-II",
    "basis_set_family": "iglo",
    "basis_set_description": "VDZP Valence Double Zeta + Polarization on All Atoms",
    "basis_set_role": "orbital",
    "basis_set_auxiliaries": {}
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/ADZP.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "basis_set_name": "jorge-ADZP",
    "basis_set_family": "jorge",
    "basis_set_description": "ADZP: Augmented double zeta valence quality plus polarization",
    "basis_set_role": "orbital",
    "basis_set_auxiliaries": {}
}
