=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/schema/metadata-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "name": "bse_basis_metadata",
    "version": "0.1",
    "url": "TODO",
    "description": "JSON for describing metadata for a single basis set",
    "type": "object",
    "additionalProperties": false,
    "required": [
        "molssi_bse_schema",
        "basis_set_name",
        "basis_set_family",
        "basis_set_description",
        "basis_set_role",
        "basis_set_auxiliaries"
    ],
    "properties":
    {
        "molssi_bse_schema": {
            "description": "Info about which schema the file follows",
            "type": "object",
            "additionalProperties": false,
            "required": [
                "schema_type",
                "schema_version"
            ],
            "properties": {
                "schema_type" : {
                    "description": "What type of BSE JSON file this is",
                    "type": "string",
                    "enum": [ "metadata" ]
                },
                "schema_version": {
                    "description": "Version of the BSE table basis set schema being used",
                    "type": "string"
                }
            }
        },
        "basis_set_name": {
            "description": "Common name for the basis set",
            "type": "string"
        },
        "basis_set_family": {
            "description": "Broad family that the basis set is from",
            "type": "string"
        },
        "basis_set_description": {
            "description": "Brief description of the basis set",
            "type": "string"
        },
        "basis_set_role": {
            "description": "Role that this basis plays in a calculation",
            "type": "string",
            "enum": [ "orbital", "rifit", "jkfit", "jfit", "admmfit", "dftxfit", "dftcfit"]
        },
        "basis_set_auxiliaries": {
            "description": "Auxiliary basis sets (fitting, etc) and how their role with his basis",
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "jfit" : { "type": "string" },
                "jkfit" : { "type": "string" },
                "rifit" : { "type": "string" },
                "admmfit" : { "type": "string" },
                "dftxfit": { "type": "string" },
                "dftcfit": { "type": "string" }
            }
        }
    }
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/jun-cc-pVT+dZ.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "basis_set_name": "jun-cc-pV(T+d)Z",
    "basis_set_family": "truhlar",
    "basis_set_description": "jun-cc-pV(T+d)Z basis of Papajak/Truhlar",
    "basis_set_role": "orbital",
    "basis_set_auxiliaries": {}
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/def2-ECP.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "basis_set_name": "def2-ECP",
    "basis_set_family": "ahlrichs",
    "basis_set_description": "ECP for use with Ahlrichs def2 basis sets",
    "basis_set_role": "orbital",
    "basis_set_auxiliaries": {}
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/may-cc-pVQ+dZ.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "basis_set_name": "may-cc-pV(Q+d)Z",
    "basis_set_family": "truhlar",
    "basis_set_description": "may-cc-pV(Q+d)Z basis of Papajak/Truhlar",
    "basis_set_role": "orbital",
    "basis_set_auxiliaries": {}
}

=== pypi-data/pypi-mirror-43/packages/basis-set-exchange/basis_set_exchange-0.6.4.tar.gz/basis_set_exchange-0.6.4/basis_set_exchange/data/STO-2G.metadata.json
{
    "molssi_bse_schema": {
        "schema_type": "metadata",
        "schema_version": "0.1"
    },
    "basis_set_name": "STO-2G",
    "basis_set_family": "sto",
    "basis_set_description": "STO-2G Minimal Basis (2 functions/AO)",
    "basis_set_role": "orbital",
    "basis_set_auxiliaries": {}
}
